<?php
declare(strict_types=1);

namespace app\showcase\service\registry;

/**
 * Showcase 表单组件能力块目录
 */
final class ShowcaseFormComponentSectionCatalog
{
    /**
     * @return array<string, list<array<string, string>>>
     */
    public static function sections(): array
    {
        return [
            'basic.text' => [
                [
                    'key' => 'basic',
                    'title' => '基础用法',
                    'summary' => '最小可用的 text 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\text\\TextBasicSection',
                ],
                [
                    'key' => 'placeholder_tips',
                    'title' => '占位符与提示',
                    'summary' => 'placeholder 与 tips 的组合。',
                    'builder' => 'app\\showcase\\service\\components\\form\\text\\TextPlaceholderSection',
                ],
                [
                    'key' => 'length_limit',
                    'title' => '必填与长度限制',
                    'summary' => 'required、min_length、max_length。',
                    'builder' => 'app\\showcase\\service\\components\\form\\text\\TextLengthSection',
                ],
                [
                    'key' => 'prefix_suffix',
                    'title' => '前缀与后缀',
                    'summary' => '文本、图标、按钮型前后缀。',
                    'builder' => 'app\\showcase\\service\\components\\form\\text\\TextPrefixSuffixSection',
                ],
                [
                    'key' => 'state',
                    'title' => '只读与禁用',
                    'summary' => 'readonly 与 disabled 状态展示。',
                    'builder' => 'app\\showcase\\service\\components\\form\\text\\TextStateSection',
                ],
                [
                    'key' => 'style',
                    'title' => '样式变体',
                    'summary' => 'rounded、flush、float。',
                    'builder' => 'app\\showcase\\service\\components\\form\\text\\TextStyleSection',
                ],
                [
                    'key' => 'datalist',
                    'title' => '自动补全 datalist',
                    'summary' => 'datalist 自动补全。',
                    'builder' => 'app\\showcase\\service\\components\\form\\text\\TextDatalistSection',
                ],
                [
                    'key' => 'group_type',
                    'title' => '前后缀分组类型',
                    'summary' => 'text、icon、button 三种分组模式。',
                    'builder' => 'app\\showcase\\service\\components\\form\\text\\TextGroupTypeSection',
                ],
                [
                    'key' => 'validation',
                    'title' => '校验与反馈状态',
                    'summary' => 'valid(true/false) 对应的校验态效果。',
                    'builder' => 'app\\showcase\\service\\components\\form\\text\\TextValidationSection',
                ],
                [
                    'key' => 'advanced_props',
                    'title' => '扩展参数与 DOM 控制',
                    'summary' => 'help、extra_class、size、id、props 等扩展能力。',
                    'builder' => 'app\\showcase\\service\\components\\form\\text\\TextAdvancedPropsSection',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务综合示例',
                    'summary' => '把常见 text 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\text\\TextProfileFormSection',
                ],
            ],
            'basic.textarea' => [
                [
                    'key' => 'basic',
                    'title' => '基础用法',
                    'summary' => '最小可用的 textarea 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\textarea\\TextareaBasicSection',
                ],
                [
                    'key' => 'placeholder_tips',
                    'title' => '占位符与提示',
                    'summary' => 'placeholder 与 tips 在多行输入中的组合。',
                    'builder' => 'app\\showcase\\service\\components\\form\\textarea\\TextareaPlaceholderSection',
                ],
                [
                    'key' => 'length_limit',
                    'title' => '必填与长度限制',
                    'summary' => 'required、max_length 与 max() 别名。',
                    'builder' => 'app\\showcase\\service\\components\\form\\textarea\\TextareaLengthSection',
                ],
                [
                    'key' => 'value_rows',
                    'title' => '默认值与行数',
                    'summary' => 'value 回显与 rows 初始行数控制。',
                    'builder' => 'app\\showcase\\service\\components\\form\\textarea\\TextareaValueRowsSection',
                ],
                [
                    'key' => 'autosize',
                    'title' => '自动增高 autosize',
                    'summary' => '根据内容自动调整 textarea 高度。',
                    'builder' => 'app\\showcase\\service\\components\\form\\textarea\\TextareaAutosizeSection',
                ],
                [
                    'key' => 'state',
                    'title' => '只读与禁用',
                    'summary' => 'readonly 与 disabled 状态展示。',
                    'builder' => 'app\\showcase\\service\\components\\form\\textarea\\TextareaStateSection',
                ],
                [
                    'key' => 'advanced_props',
                    'title' => '扩展参数与 DOM 控制',
                    'summary' => 'help、id、size、class、props 等扩展能力。',
                    'builder' => 'app\\showcase\\service\\components\\form\\textarea\\TextareaAdvancedPropsSection',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务综合示例',
                    'summary' => '把常见 textarea 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\textarea\\TextareaProfileFormSection',
                ],
            ],
            'basic.number' => [
                [
                    'key' => 'basic',
                    'title' => '基础用法',
                    'summary' => '最小可用的 number 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\number\\NumberBasicSection',
                ],
                [
                    'key' => 'placeholder_tips',
                    'title' => '占位符与提示',
                    'summary' => 'placeholder 与 tips 在数值场景中的组合。',
                    'builder' => 'app\\showcase\\service\\components\\form\\number\\NumberPlaceholderSection',
                ],
                [
                    'key' => 'range_limit',
                    'title' => '最小值与最大值',
                    'summary' => 'min_length、max_length 与 min()/max() 别名。',
                    'builder' => 'app\\showcase\\service\\components\\form\\number\\NumberRangeSection',
                ],
                [
                    'key' => 'step',
                    'title' => '步进值 step',
                    'summary' => '通过 step 控制数值增减步长。',
                    'builder' => 'app\\showcase\\service\\components\\form\\number\\NumberStepSection',
                ],
                [
                    'key' => 'prefix_suffix',
                    'title' => '前缀与后缀',
                    'summary' => '货币符号、单位和业务上下文提示。',
                    'builder' => 'app\\showcase\\service\\components\\form\\number\\NumberPrefixSuffixSection',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与业务默认数',
                    'summary' => '通过 value 提供默认数或编辑态回显值。',
                    'builder' => 'app\\showcase\\service\\components\\form\\number\\NumberDefaultValueSection',
                ],
                [
                    'key' => 'state',
                    'title' => '只读与禁用',
                    'summary' => 'readonly 与 disabled 状态展示。',
                    'builder' => 'app\\showcase\\service\\components\\form\\number\\NumberStateSection',
                ],
                [
                    'key' => 'style',
                    'title' => '样式变体',
                    'summary' => 'rounded、flush、float 三种常见视觉风格。',
                    'builder' => 'app\\showcase\\service\\components\\form\\number\\NumberStyleSection',
                ],
                [
                    'key' => 'validation',
                    'title' => '校验与反馈状态',
                    'summary' => 'valid(true/false) 对应的校验态效果。',
                    'builder' => 'app\\showcase\\service\\components\\form\\number\\NumberValidationSection',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务综合示例',
                    'summary' => '把常见 number 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\number\\NumberProfileFormSection',
                ],
            ],
            'basic.password' => [
                [
                    'key' => 'basic',
                    'title' => '基础密码输入',
                    'summary' => '最小可用的 password 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\password\\PasswordSectionBuilder',
                ],
                [
                    'key' => 'placeholder_tips',
                    'title' => '占位符与提示',
                    'summary' => 'placeholder 与 tips 在密码场景中的组合。',
                    'builder' => 'app\\showcase\\service\\components\\form\\password\\PasswordSectionBuilder',
                ],
                [
                    'key' => 'length_limit',
                    'title' => '长度限制',
                    'summary' => 'min_length、max_length 约束密码长度。',
                    'builder' => 'app\\showcase\\service\\components\\form\\password\\PasswordSectionBuilder',
                ],
                [
                    'key' => 'switch_strength',
                    'title' => '显示切换与强度提示',
                    'summary' => '通过 switch 与 strength 增强密码输入体验。',
                    'builder' => 'app\\showcase\\service\\components\\form\\password\\PasswordSectionBuilder',
                ],
                [
                    'key' => 'prefix_style',
                    'title' => '前后缀与样式',
                    'summary' => '图标前缀、圆角、扁平、浮动标签等视觉能力。',
                    'builder' => 'app\\showcase\\service\\components\\form\\password\\PasswordSectionBuilder',
                ],
                [
                    'key' => 'state',
                    'title' => '只读与禁用',
                    'summary' => 'readonly 与 disabled 状态展示。',
                    'builder' => 'app\\showcase\\service\\components\\form\\password\\PasswordSectionBuilder',
                ],
                [
                    'key' => 'validation',
                    'title' => '校验与反馈状态',
                    'summary' => 'valid(true/false) 对应的校验态效果。',
                    'builder' => 'app\\showcase\\service\\components\\form\\password\\PasswordSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把常见 password 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\password\\PasswordSectionBuilder',
                ],
            ],
            'basic.switch' => [
                [
                    'key' => 'basic',
                    'title' => '基础用法',
                    'summary' => '最小可用的 switch 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\switch\\SwitchBasicSection',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与开关状态',
                    'summary' => 'value 决定默认开启或默认关闭。',
                    'builder' => 'app\\showcase\\service\\components\\form\\switch\\SwitchDefaultValueSection',
                ],
                [
                    'key' => 'title',
                    'title' => '标题说明 title',
                    'summary' => '通过 title 在开关右侧补充说明。',
                    'builder' => 'app\\showcase\\service\\components\\form\\switch\\SwitchTitleSection',
                ],
                [
                    'key' => 'disabled',
                    'title' => '禁用状态',
                    'summary' => '通过 disabled 锁定开关交互。',
                    'builder' => 'app\\showcase\\service\\components\\form\\switch\\SwitchDisabledSection',
                ],
                [
                    'key' => 'inline',
                    'title' => '内联展示 inline',
                    'summary' => '多个开关以内联方式并排展示。',
                    'builder' => 'app\\showcase\\service\\components\\form\\switch\\SwitchInlineSection',
                ],
                [
                    'key' => 'multi_switch',
                    'title' => '多开关组合',
                    'summary' => '通过 options 一次性渲染多枚开关。',
                    'builder' => 'app\\showcase\\service\\components\\form\\switch\\SwitchMultiSection',
                ],
                [
                    'key' => 'submission_notice',
                    'title' => '提交注意事项',
                    'summary' => '强调 switch 未选中不提交的后端处理要求。',
                    'builder' => 'app\\showcase\\service\\components\\form\\switch\\SwitchSubmissionNoticeSection',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务综合示例',
                    'summary' => '把常见 switch 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\switch\\SwitchProfileFormSection',
                ],
            ],
            'basic.hidden' => [
                [
                    'key' => 'basic',
                    'title' => '基础隐藏值',
                    'summary' => '最小可用的 hidden 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\hidden\\HiddenSectionBuilder',
                ],
                [
                    'key' => 'multiple_fields',
                    'title' => '多字段传递',
                    'summary' => '同时提交多个上下文字段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\hidden\\HiddenSectionBuilder',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 提供默认值和编辑态回显值。',
                    'builder' => 'app\\showcase\\service\\components\\form\\hidden\\HiddenSectionBuilder',
                ],
                [
                    'key' => 'edit_primary_key',
                    'title' => '编辑态主键传递',
                    'summary' => '编辑页常见的主键与上下文标识传递方式。',
                    'builder' => 'app\\showcase\\service\\components\\form\\hidden\\HiddenSectionBuilder',
                ],
                [
                    'key' => 'security_notice',
                    'title' => '安全提示组合示例',
                    'summary' => '通过 hidden 与 static 说明块组合演示 hidden 值不可直接信任，后端仍需校验。',
                    'builder' => 'app\\showcase\\service\\components\\form\\hidden\\HiddenSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把 hidden 与普通输入组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\hidden\\HiddenSectionBuilder',
                ],
            ],
            'basic.html' => [
                [
                    'key' => 'basic',
                    'title' => '基础提示内容',
                    'summary' => '最常见的提示区 HTML 输出。',
                    'builder' => 'app\\showcase\\service\\components\\form\\html\\HtmlSectionBuilder',
                ],
                [
                    'key' => 'list',
                    'title' => '说明列表',
                    'summary' => '使用列表说明操作步骤或规则。',
                    'builder' => 'app\\showcase\\service\\components\\form\\html\\HtmlSectionBuilder',
                ],
                [
                    'key' => 'card',
                    'title' => '信息卡片',
                    'summary' => '通过卡片容器展示更丰富的上下文信息。',
                    'builder' => 'app\\showcase\\service\\components\\form\\html\\HtmlSectionBuilder',
                ],
                [
                    'key' => 'danger',
                    'title' => '危险操作警告',
                    'summary' => '删除、重置等不可逆动作前的提醒区域。',
                    'builder' => 'app\\showcase\\service\\components\\form\\html\\HtmlSectionBuilder',
                ],
                [
                    'key' => 'status',
                    'title' => '图标与状态',
                    'summary' => '结合图标、badge 展示审核状态或运行状态。',
                    'builder' => 'app\\showcase\\service\\components\\form\\html\\HtmlSectionBuilder',
                ],
                [
                    'key' => 'compare_static',
                    'title' => '与 static 的区别',
                    'summary' => '解释 html 与 static 在用途上的差异。',
                    'builder' => 'app\\showcase\\service\\components\\form\\html\\HtmlSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把 html 区块和业务输入项组合成真实表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\html\\HtmlSectionBuilder',
                ],
            ],
            'basic.static' => [
                [
                    'key' => 'basic',
                    'title' => '基础静态展示',
                    'summary' => '最小可用的 static 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\static\\StaticSectionBuilder',
                ],
                [
                    'key' => 'send',
                    'title' => 'send 提交数据',
                    'summary' => '静态展示同时随表单提交原值。',
                    'builder' => 'app\\showcase\\service\\components\\form\\static\\StaticSectionBuilder',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '显示编辑态已有值与系统回填值。',
                    'builder' => 'app\\showcase\\service\\components\\form\\static\\StaticSectionBuilder',
                ],
                [
                    'key' => 'raw',
                    'title' => 'HTML 内容 raw',
                    'summary' => '通过 raw 渲染 HTML 内容而不是转义文本。',
                    'builder' => 'app\\showcase\\service\\components\\form\\static\\StaticSectionBuilder',
                ],
                [
                    'key' => 'relation_info',
                    'title' => '关联信息展示',
                    'summary' => '展示部门、角色、来源等关联信息。',
                    'builder' => 'app\\showcase\\service\\components\\form\\static\\StaticSectionBuilder',
                ],
                [
                    'key' => 'compare_hidden',
                    'title' => '与 hidden 的区别',
                    'summary' => '说明 static 和 hidden 在展示/提交层面的差别。',
                    'builder' => 'app\\showcase\\service\\components\\form\\static\\StaticSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把 static 与可编辑字段组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\static\\StaticSectionBuilder',
                ],
            ],
            'basic.button' => [
                [
                    'key' => 'basic',
                    'title' => '基础按钮',
                    'summary' => '最常见的 button 展示方式。',
                    'builder' => 'app\\showcase\\service\\components\\form\\button\\ButtonSectionBuilder',
                ],
                [
                    'key' => 'color_style',
                    'title' => '颜色与样式',
                    'summary' => '主色、幽灵、描边等颜色风格。',
                    'builder' => 'app\\showcase\\service\\components\\form\\button\\ButtonSectionBuilder',
                ],
                [
                    'key' => 'icon',
                    'title' => '图标按钮',
                    'summary' => '图标与文本组合，或纯图标按钮。',
                    'builder' => 'app\\showcase\\service\\components\\form\\button\\ButtonSectionBuilder',
                ],
                [
                    'key' => 'link',
                    'title' => '链接按钮',
                    'summary' => '按钮外观但跳转到链接地址。',
                    'builder' => 'app\\showcase\\service\\components\\form\\button\\ButtonSectionBuilder',
                ],
                [
                    'key' => 'shape',
                    'title' => '形状变体',
                    'summary' => '方形、药丸形等视觉形态。',
                    'builder' => 'app\\showcase\\service\\components\\form\\button\\ButtonSectionBuilder',
                ],
                [
                    'key' => 'disabled',
                    'title' => '禁用状态',
                    'summary' => '不可点击时的展示与提示。',
                    'builder' => 'app\\showcase\\service\\components\\form\\button\\ButtonSectionBuilder',
                ],
                [
                    'key' => 'svg',
                    'title' => 'SVG 图标',
                    'summary' => '使用内联 SVG 提供更自由的图标表现。',
                    'builder' => 'app\\showcase\\service\\components\\form\\button\\ButtonSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把 button 与静态说明、输入项组合成真实表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\button\\ButtonSectionBuilder',
                ],
            ],
            'basic.button_group' => [
                [
                    'key' => 'basic',
                    'title' => '基础按钮组',
                    'summary' => '最小可用的 button_group 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\button_group\\ButtonGroupSectionBuilder',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 控制当前激活项。',
                    'builder' => 'app\\showcase\\service\\components\\form\\button_group\\ButtonGroupSectionBuilder',
                ],
                [
                    'key' => 'icon',
                    'title' => '图标按钮组',
                    'summary' => '把按钮组渲染为图标切换器。',
                    'builder' => 'app\\showcase\\service\\components\\form\\button_group\\ButtonGroupSectionBuilder',
                ],
                [
                    'key' => 'vertical',
                    'title' => '垂直布局',
                    'summary' => '把按钮组切换为垂直堆叠布局。',
                    'builder' => 'app\\showcase\\service\\components\\form\\button_group\\ButtonGroupSectionBuilder',
                ],
                [
                    'key' => 'group_class',
                    'title' => '自定义 group_class',
                    'summary' => '通过 group_class 控制按钮组容器类名。',
                    'builder' => 'app\\showcase\\service\\components\\form\\button_group\\ButtonGroupSectionBuilder',
                ],
                [
                    'key' => 'notice',
                    'title' => '值处理提示',
                    'summary' => '说明 button_group 最终提交的是选中值。',
                    'builder' => 'app\\showcase\\service\\components\\form\\button_group\\ButtonGroupSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把 button_group 与搜索、视图切换组合成真实表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\button_group\\ButtonGroupSectionBuilder',
                ],
            ],
            'basic.mask' => [
                [
                    'key' => 'basic',
                    'title' => '基础掩码',
                    'summary' => '最小可用的 mask 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\mask\\MaskSectionBuilder',
                ],
                [
                    'key' => 'phone',
                    'title' => '手机号格式',
                    'summary' => '使用掩码约束手机号输入格式。',
                    'builder' => 'app\\showcase\\service\\components\\form\\mask\\MaskSectionBuilder',
                ],
                [
                    'key' => 'date_time',
                    'title' => '日期与时间格式',
                    'summary' => '通过掩码引导日期或时间输入格式。',
                    'builder' => 'app\\showcase\\service\\components\\form\\mask\\MaskSectionBuilder',
                ],
                [
                    'key' => 'id_code',
                    'title' => '证件与编号格式',
                    'summary' => '适合身份证、合同号、业务编号等固定格式输入。',
                    'builder' => 'app\\showcase\\service\\components\\form\\mask\\MaskSectionBuilder',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 回显已格式化的编辑态值。',
                    'builder' => 'app\\showcase\\service\\components\\form\\mask\\MaskSectionBuilder',
                ],
                [
                    'key' => 'notice',
                    'title' => '实现与提交注意事项',
                    'summary' => '说明 mask 的真实参数和后端处理边界。',
                    'builder' => 'app\\showcase\\service\\components\\form\\mask\\MaskSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把 mask 与普通输入组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\mask\\MaskSectionBuilder',
                ],
            ],
            'choice.radio' => [
                [
                    'key' => 'basic',
                    'title' => '基础单选',
                    'summary' => '最小可用的 radio 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\radio\\RadioBasicSection',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 指定初始选中值或编辑态回显。',
                    'builder' => 'app\\showcase\\service\\components\\form\\radio\\RadioDefaultValueSection',
                ],
                [
                    'key' => 'options',
                    'title' => '选项配置',
                    'summary' => '使用 options 承载明确的互斥选项列表。',
                    'builder' => 'app\\showcase\\service\\components\\form\\radio\\RadioOptionsSection',
                ],
                [
                    'key' => 'inline',
                    'title' => 'inline 水平排列',
                    'summary' => '多个单选项以内联方式横向排布。',
                    'builder' => 'app\\showcase\\service\\components\\form\\radio\\RadioInlineSection',
                ],
                [
                    'key' => 'disabled',
                    'title' => '禁用状态',
                    'summary' => '通过 disabled 锁定不可编辑的单选项。',
                    'builder' => 'app\\showcase\\service\\components\\form\\radio\\RadioDisabledSection',
                ],
                [
                    'key' => 'required',
                    'title' => '必填校验',
                    'summary' => 'required 配合提示文案展示必选场景。',
                    'builder' => 'app\\showcase\\service\\components\\form\\radio\\RadioRequiredSection',
                ],
                [
                    'key' => 'when',
                    'title' => 'when 条件联动',
                    'summary' => 'radio 作为上游驱动项控制下游字段显示与必填。',
                    'builder' => 'app\\showcase\\service\\components\\form\\radio\\RadioWhenSection',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把常见 radio 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\radio\\RadioProfileFormSection',
                ],
            ],
            'choice.radio_group' => [
                [
                    'key' => 'basic',
                    'title' => '基础卡片单选',
                    'summary' => '最小可用的 radio_group 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\radio_group\\RadioGroupBasicSection',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 指定默认选中项或编辑态回显。',
                    'builder' => 'app\\showcase\\service\\components\\form\\radio_group\\RadioGroupDefaultValueSection',
                ],
                [
                    'key' => 'rich_option',
                    'title' => '富文案选项',
                    'summary' => '利用卡片布局承载图标、标识、说明文案等视觉化内容。',
                    'builder' => 'app\\showcase\\service\\components\\form\\radio_group\\RadioGroupRichOptionSection',
                ],
                [
                    'key' => 'object_option',
                    'title' => '组件对象选项',
                    'summary' => '通过 Payment、Flag、Avatar 等组件对象生成可复用的选项内容。',
                    'builder' => 'app\\showcase\\service\\components\\form\\radio_group\\RadioGroupObjectOptionSection',
                ],
                [
                    'key' => 'disabled',
                    'title' => '禁用状态',
                    'summary' => '通过 disabled 锁定不可选的卡片项。',
                    'builder' => 'app\\showcase\\service\\components\\form\\radio_group\\RadioGroupDisabledSection',
                ],
                [
                    'key' => 'required',
                    'title' => '必填校验',
                    'summary' => 'required 配合提示文案展示必选场景。',
                    'builder' => 'app\\showcase\\service\\components\\form\\radio_group\\RadioGroupRequiredSection',
                ],
                [
                    'key' => 'pricing_plan',
                    'title' => '套餐型展示',
                    'summary' => '以套餐、版本、价格档位等业务视角展示卡片单选。',
                    'builder' => 'app\\showcase\\service\\components\\form\\radio_group\\RadioGroupPricingPlanSection',
                ],
                [
                    'key' => 'when',
                    'title' => 'when 条件联动',
                    'summary' => 'radio_group 作为上游驱动项控制下游字段显隐与必填。',
                    'builder' => 'app\\showcase\\service\\components\\form\\radio_group\\RadioGroupWhenSection',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把常见 radio_group 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\radio_group\\RadioGroupProfileFormSection',
                ],
            ],
            'choice.select' => [
                [
                    'key' => 'basic',
                    'title' => '基础下拉选择',
                    'summary' => '最小可用的 select 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select\\SelectBasicSection',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 指定初始选中项或编辑态回显。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select\\SelectDefaultValueSection',
                ],
                [
                    'key' => 'placeholder',
                    'title' => '占位符提示',
                    'summary' => '通过 placeholder 自定义空选项提示文案。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select\\SelectPlaceholderSection',
                ],
                [
                    'key' => 'multiple',
                    'title' => 'multiple 多选',
                    'summary' => '启用 multiple 后支持同一字段选择多个值。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select\\SelectMultipleSection',
                ],
                [
                    'key' => 'multiple_value',
                    'title' => '多选默认值',
                    'summary' => '通过逗号分隔的 value 回显多个已选值。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select\\SelectMultipleValueSection',
                ],
                [
                    'key' => 'disabled',
                    'title' => '禁用状态',
                    'summary' => '通过 disabled 锁定整个下拉框交互。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select\\SelectDisabledSection',
                ],
                [
                    'key' => 'option_disabled',
                    'title' => '禁用指定选项',
                    'summary' => '通过 disabled 数组或字符串禁用部分选项。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select\\SelectOptionDisabledSection',
                ],
                [
                    'key' => 'group',
                    'title' => '分组选项',
                    'summary' => '通过 group 或多维 options 展示 optgroup 结构。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select\\SelectGroupSection',
                ],
                [
                    'key' => 'advanced_props',
                    'title' => '扩展参数与 DOM 控制',
                    'summary' => 'help、id、class、props 等扩展参数。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select\\SelectAdvancedPropsSection',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把常见 select 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select\\SelectProfileFormSection',
                ],
            ],
            'choice.select2' => [
                [
                    'key' => 'basic',
                    'title' => '基础增强下拉',
                    'summary' => '最小可用的 select2 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select2\\Select2BasicSection',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 指定默认选中项或编辑态回显。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select2\\Select2DefaultValueSection',
                ],
                [
                    'key' => 'placeholder',
                    'title' => '占位符提示',
                    'summary' => '通过 placeholder 定制搜索型下拉的空态提示。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select2\\Select2PlaceholderSection',
                ],
                [
                    'key' => 'multiple',
                    'title' => 'multiple 多选',
                    'summary' => '启用 multiple 后支持同一字段选择多个值。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select2\\Select2MultipleSection',
                ],
                [
                    'key' => 'multiple_value',
                    'title' => '多选默认值',
                    'summary' => '通过逗号分隔 value 回显多个已选项。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select2\\Select2MultipleValueSection',
                ],
                [
                    'key' => 'option_disabled',
                    'title' => '禁用指定选项',
                    'summary' => '通过 disabled 数组或字符串禁用部分候选项。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select2\\Select2OptionDisabledSection',
                ],
                [
                    'key' => 'group',
                    'title' => '分组选项',
                    'summary' => '通过 group 或多维 options 展示 optgroup 结构。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select2\\Select2GroupSection',
                ],
                [
                    'key' => 'ajax_builtin',
                    'title' => '内置 ajax 数据源',
                    'summary' => '使用框架内置 `admin/api/getSelectAjax` 契约拉取远程选项。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select2\\Select2AjaxBuiltinSection',
                ],
                [
                    'key' => 'ajax_custom',
                    'title' => '自定义 ajax URL',
                    'summary' => '通过字符串 URL 接入自定义远程接口。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select2\\Select2AjaxCustomSection',
                ],
                [
                    'key' => 'native_options',
                    'title' => '原生 _options 配置',
                    'summary' => '透传 Select2 原生参数，如 `minimumResultsForSearch`、`theme` 等。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select2\\Select2NativeOptionsSection',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把常见 select2 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select2\\Select2ProfileFormSection',
                ],
            ],
            'choice.linkage' => [
                [
                    'key' => 'basic',
                    'title' => '基础远程联动',
                    'summary' => '最小可用的 linkage 远程联动配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\linkage\\LinkageSectionBuilder',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 回显多级默认值或编辑态数据。',
                    'builder' => 'app\\showcase\\service\\components\\form\\linkage\\LinkageSectionBuilder',
                ],
                [
                    'key' => 'level_labels',
                    'title' => '级别占位符与标签',
                    'summary' => '通过 levels 配置每一级的 key、label 和 placeholder。',
                    'builder' => 'app\\showcase\\service\\components\\form\\linkage\\LinkageSectionBuilder',
                ],
                [
                    'key' => 'level_url',
                    'title' => '按级别覆盖 url',
                    'summary' => '给不同级别指定独立请求地址或参数映射。',
                    'builder' => 'app\\showcase\\service\\components\\form\\linkage\\LinkageSectionBuilder',
                ],
                [
                    'key' => 'submit_all',
                    'title' => 'submit_all 与末级提交',
                    'summary' => '控制是提交所有级别值，还是只提交最终级结果。',
                    'builder' => 'app\\showcase\\service\\components\\form\\linkage\\LinkageSectionBuilder',
                ],
                [
                    'key' => 'multiple',
                    'title' => 'multiple 末级多选',
                    'summary' => '在最后一级启用 multiple，让末级支持多选。',
                    'builder' => 'app\\showcase\\service\\components\\form\\linkage\\LinkageSectionBuilder',
                ],
                [
                    'key' => 'request_fields',
                    'title' => 'request_fields 与 params',
                    'summary' => '控制每一级请求参数的字段名映射与固定参数。',
                    'builder' => 'app\\showcase\\service\\components\\form\\linkage\\LinkageSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把 linkage 与渠道、仓库等字段组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\linkage\\LinkageSectionBuilder',
                ],
            ],
            'choice.linkages' => [
                [
                    'key' => 'basic',
                    'title' => '基础快速联动',
                    'summary' => '最小可用的 linkages 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\linkages\\LinkagesSectionBuilder',
                ],
                [
                    'key' => 'levels',
                    'title' => 'levels 数量与命名',
                    'summary' => '通过整数、字符串或完整数组定义联动级数与名称。',
                    'builder' => 'app\\showcase\\service\\components\\form\\linkages\\LinkagesSectionBuilder',
                ],
                [
                    'key' => 'fields_root',
                    'title' => 'fields 与 root_pid',
                    'summary' => '配置字段映射和根节点 pid，适配不同树表结构。',
                    'builder' => 'app\\showcase\\service\\components\\form\\linkages\\LinkagesSectionBuilder',
                ],
                [
                    'key' => 'prefix_connection',
                    'title' => 'prefix 与 connection',
                    'summary' => '控制是否带前缀查询以及指定数据库连接。',
                    'builder' => 'app\\showcase\\service\\components\\form\\linkages\\LinkagesSectionBuilder',
                ],
                [
                    'key' => 'filters',
                    'title' => 'filters 分级筛选',
                    'summary' => '为不同层级附加固定筛选条件。',
                    'builder' => 'app\\showcase\\service\\components\\form\\linkages\\LinkagesSectionBuilder',
                ],
                [
                    'key' => 'submit_all',
                    'title' => 'submit_all 与末级提交',
                    'summary' => '控制是提交所有级别值，还是只提交末级结果。',
                    'builder' => 'app\\showcase\\service\\components\\form\\linkages\\LinkagesSectionBuilder',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 回显已有联动路径或默认末级值。',
                    'builder' => 'app\\showcase\\service\\components\\form\\linkages\\LinkagesSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把 linkages 与分类名称、排序等字段组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\linkages\\LinkagesSectionBuilder',
                ],
            ],
            'choice.checkbox' => [
                [
                    'key' => 'basic',
                    'title' => '基础多选',
                    'summary' => '最小可用的 checkbox 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\checkbox\\CheckboxSectionBuilder',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 指定默认勾选项或编辑态回显。',
                    'builder' => 'app\\showcase\\service\\components\\form\\checkbox\\CheckboxSectionBuilder',
                ],
                [
                    'key' => 'inline',
                    'title' => 'inline 横向排列',
                    'summary' => '通过 inline 开启水平排列。',
                    'builder' => 'app\\showcase\\service\\components\\form\\checkbox\\CheckboxSectionBuilder',
                ],
                [
                    'key' => 'disabled',
                    'title' => '禁用状态',
                    'summary' => '通过 disabled 设置为 true 一键禁用全部选项，或传数组禁用部分选项。',
                    'builder' => 'app\\showcase\\service\\components\\form\\checkbox\\CheckboxSectionBuilder',
                ],
                [
                    'key' => 'remark',
                    'title' => '备注说明',
                    'summary' => '通过 remark 或 `选项#说明` 方式补充说明文案。',
                    'builder' => 'app\\showcase\\service\\components\\form\\checkbox\\CheckboxSectionBuilder',
                ],
                [
                    'key' => 'option_string',
                    'title' => '选项字符串解析',
                    'summary' => '说明 `选项#说明` 自动拆分成文案与备注的能力。',
                    'builder' => 'app\\showcase\\service\\components\\form\\checkbox\\CheckboxSectionBuilder',
                ],
                [
                    'key' => 'notice',
                    'title' => '值处理提示',
                    'summary' => '说明多选值的提交结构与后端处理要点。',
                    'builder' => 'app\\showcase\\service\\components\\form\\checkbox\\CheckboxSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把常见 checkbox 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\checkbox\\CheckboxSectionBuilder',
                ],
            ],
            'choice.checkbox_group' => [
                [
                    'key' => 'basic',
                    'title' => '基础卡片多选',
                    'summary' => '最小可用的 checkbox_group 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\checkbox_group\\CheckboxGroupSectionBuilder',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 指定默认选中的卡片项。',
                    'builder' => 'app\\showcase\\service\\components\\form\\checkbox_group\\CheckboxGroupSectionBuilder',
                ],
                [
                    'key' => 'required',
                    'title' => '必填场景',
                    'summary' => '通过 required 强调必须选择至少一个卡片项。',
                    'builder' => 'app\\showcase\\service\\components\\form\\checkbox_group\\CheckboxGroupSectionBuilder',
                ],
                [
                    'key' => 'disabled',
                    'title' => '禁用状态',
                    'summary' => '通过 disabled 禁用全部或部分卡片项。',
                    'builder' => 'app\\showcase\\service\\components\\form\\checkbox_group\\CheckboxGroupSectionBuilder',
                ],
                [
                    'key' => 'layout',
                    'title' => '布局与文案',
                    'summary' => '通过 HTML 文案和 class 增强卡片展示层次。',
                    'builder' => 'app\\showcase\\service\\components\\form\\checkbox_group\\CheckboxGroupSectionBuilder',
                ],
                [
                    'key' => 'notice',
                    'title' => '值处理提示',
                    'summary' => '说明 checkbox_group 的数组值提交、JSON/逗号串存储与稳定 value 治理建议。',
                    'builder' => 'app\\showcase\\service\\components\\form\\checkbox_group\\CheckboxGroupSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把常见 checkbox_group 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\checkbox_group\\CheckboxGroupSectionBuilder',
                ],
            ],
            'choice.select_group' => [
                [
                    'key' => 'basic',
                    'title' => '基础标签多选',
                    'summary' => '最小可用的 select_group 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select_group\\SelectGroupSectionBuilder',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 指定默认选中的标签项。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select_group\\SelectGroupSectionBuilder',
                ],
                [
                    'key' => 'disabled',
                    'title' => '禁用状态',
                    'summary' => '通过 disabled 禁用全部或部分标签项。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select_group\\SelectGroupSectionBuilder',
                ],
                [
                    'key' => 'rounded',
                    'title' => '圆角样式',
                    'summary' => '通过 rounded 切换胶囊式标签外观。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select_group\\SelectGroupSectionBuilder',
                ],
                [
                    'key' => 'notice_scale',
                    'title' => '选项规模建议',
                    'summary' => '说明 select_group 更适合短标签、少量候选项的场景。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select_group\\SelectGroupSectionBuilder',
                ],
                [
                    'key' => 'notice',
                    'title' => '值处理提示',
                    'summary' => '说明 select_group 的数组值提交与存储建议。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select_group\\SelectGroupSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把常见 select_group 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\select_group\\SelectGroupSectionBuilder',
                ],
            ],
            'choice.tags' => [
                [
                    'key' => 'basic',
                    'title' => '基础标签输入',
                    'summary' => '最小可用的 tags 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\tags\\TagsSectionBuilder',
                ],
                [
                    'key' => 'placeholder_tips',
                    'title' => '提示与占位符',
                    'summary' => 'placeholder 与 tips 在标签输入中的组合。',
                    'builder' => 'app\\showcase\\service\\components\\form\\tags\\TagsSectionBuilder',
                ],
                [
                    'key' => 'readonly_default',
                    'title' => '只读与默认值',
                    'summary' => '通过 value 和 readonly 展示已有标签及只读状态。',
                    'builder' => 'app\\showcase\\service\\components\\form\\tags\\TagsSectionBuilder',
                ],
                [
                    'key' => 'whitelist',
                    'title' => '白名单选项',
                    'summary' => '通过 options.whitelist 约束候选标签范围。',
                    'builder' => 'app\\showcase\\service\\components\\form\\tags\\TagsSectionBuilder',
                ],
                [
                    'key' => 'style_size',
                    'title' => '样式与尺寸',
                    'summary' => '通过 rounded、flush、size、class 等控制视觉风格。',
                    'builder' => 'app\\showcase\\service\\components\\form\\tags\\TagsSectionBuilder',
                ],
                [
                    'key' => 'notice',
                    'title' => '值处理提示',
                    'summary' => '说明 tags 的值结构、白名单与后端处理建议。',
                    'builder' => 'app\\showcase\\service\\components\\form\\tags\\TagsSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把常见 tags 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\tags\\TagsSectionBuilder',
                ],
            ],
            'choice.color' => [
                [
                    'key' => 'basic',
                    'title' => '基础取色器',
                    'summary' => '最小可用的 color 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\color\\ColorSectionBuilder',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 提供初始颜色值或编辑态回显值。',
                    'builder' => 'app\\showcase\\service\\components\\form\\color\\ColorSectionBuilder',
                ],
                [
                    'key' => 'alpha_format',
                    'title' => '颜色格式与透明度',
                    'summary' => '通过 options 控制 format 与 alpha 能力。',
                    'builder' => 'app\\showcase\\service\\components\\form\\color\\ColorSectionBuilder',
                ],
                [
                    'key' => 'theme_swatches',
                    'title' => '预设色与主题样式',
                    'summary' => '使用 swatches、theme 等配置优化选色体验。',
                    'builder' => 'app\\showcase\\service\\components\\form\\color\\ColorSectionBuilder',
                ],
                [
                    'key' => 'actions',
                    'title' => '显示按钮与交互开关',
                    'summary' => 'clearButton、closeButton、formatToggle 等交互配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\color\\ColorSectionBuilder',
                ],
                [
                    'key' => 'group_class',
                    'title' => 'group_class 与布局',
                    'summary' => '自定义颜色输入容器类名与展示布局。',
                    'builder' => 'app\\showcase\\service\\components\\form\\color\\ColorSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把 color 与标题、状态等字段组合成真实配置表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\color\\ColorSectionBuilder',
                ],
            ],
            'choice.color_select' => [
                [
                    'key' => 'basic',
                    'title' => '基础预设颜色',
                    'summary' => '最小可用的 color_select 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\color_select\\ColorSelectSectionBuilder',
                ],
                [
                    'key' => 'circle',
                    'title' => '圆形样式 circle',
                    'summary' => '将颜色项切换为圆形视觉样式。',
                    'builder' => 'app\\showcase\\service\\components\\form\\color_select\\ColorSelectSectionBuilder',
                ],
                [
                    'key' => 'custom_values',
                    'title' => '自定义颜色值',
                    'summary' => '支持主题色名、自定义颜色值和完整样式对象。',
                    'builder' => 'app\\showcase\\service\\components\\form\\color_select\\ColorSelectSectionBuilder',
                ],
                [
                    'key' => 'multiple',
                    'title' => 'multiple 多选',
                    'summary' => '把颜色选择切换为多选模式。',
                    'builder' => 'app\\showcase\\service\\components\\form\\color_select\\ColorSelectSectionBuilder',
                ],
                [
                    'key' => 'disabled',
                    'title' => '禁用指定颜色',
                    'summary' => '禁用全部或指定颜色项。',
                    'builder' => 'app\\showcase\\service\\components\\form\\color_select\\ColorSelectSectionBuilder',
                ],
                [
                    'key' => 'notice',
                    'title' => '别名与类型说明',
                    'summary' => '说明 color_select 的类型命名与值结构。',
                    'builder' => 'app\\showcase\\service\\components\\form\\color_select\\ColorSelectSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把 color_select 与标签名称等字段组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\color_select\\ColorSelectSectionBuilder',
                ],
            ],
            'choice.icon' => [
                [
                    'key' => 'basic',
                    'title' => '基础图标选择',
                    'summary' => '最小可用的 icon 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\icon\\IconSectionBuilder',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回显',
                    'summary' => '通过 value 展示当前已选图标 class。',
                    'builder' => 'app\\showcase\\service\\components\\form\\icon\\IconSectionBuilder',
                ],
                [
                    'key' => 'placeholder',
                    'title' => '占位符与默认预览图标',
                    'summary' => '使用 options 配置 placeholder 与默认图标预览。',
                    'builder' => 'app\\showcase\\service\\components\\form\\icon\\IconSectionBuilder',
                ],
                [
                    'key' => 'libs_files',
                    'title' => '扩展图标库文件',
                    'summary' => '通过 libsFile / libsFiles 追加自定义图标库定义。',
                    'builder' => 'app\\showcase\\service\\components\\form\\icon\\IconSectionBuilder',
                ],
                [
                    'key' => 'notice',
                    'title' => '配置与使用提示',
                    'summary' => '说明图标库 CSS、返回值和配置边界。',
                    'builder' => 'app\\showcase\\service\\components\\form\\icon\\IconSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把 icon 与菜单名称、路由字段组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\icon\\IconSectionBuilder',
                ],
            ],
            'datetime.date' => [
                [
                    'key' => 'basic',
                    'title' => '基础用法',
                    'summary' => '最小可用的 date 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\date\\DateBasicSection',
                ],
                [
                    'key' => 'placeholder_icon',
                    'title' => '占位符与图标',
                    'summary' => 'placeholder 与 icon 的组合配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\date\\DatePlaceholderIconSection',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 指定默认日期或编辑态回显。',
                    'builder' => 'app\\showcase\\service\\components\\form\\date\\DateDefaultValueSection',
                ],
                [
                    'key' => 'style',
                    'title' => '样式变体',
                    'summary' => 'rounded、flush 等常见日期输入视觉样式。',
                    'builder' => 'app\\showcase\\service\\components\\form\\date\\DateStyleSection',
                ],
                [
                    'key' => 'state',
                    'title' => '只读与禁用',
                    'summary' => 'readonly 与 disabled 状态展示。',
                    'builder' => 'app\\showcase\\service\\components\\form\\date\\DateStateSection',
                ],
                [
                    'key' => 'native_options',
                    'title' => '原生 options 配置',
                    'summary' => '透传 AirDatepicker 原生参数，如 `dateFormat`、`multipleDates`、`autoClose`。',
                    'builder' => 'app\\showcase\\service\\components\\form\\date\\DateNativeOptionsSection',
                ],
                [
                    'key' => 'value_format',
                    'title' => '值格式与多日期提示',
                    'summary' => '说明 value 回显格式与数组值在 date 组件中的表现。',
                    'builder' => 'app\\showcase\\service\\components\\form\\date\\DateValueFormatSection',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把常见 date 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\date\\DateProfileFormSection',
                ],
            ],
            'datetime.date_range' => [
                [
                    'key' => 'basic',
                    'title' => '基础用法',
                    'summary' => '最小可用的 date_range 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\date_range\\DateRangeBasicSection',
                ],
                [
                    'key' => 'placeholder_icon',
                    'title' => '占位符与图标',
                    'summary' => 'placeholder 与 icon 的组合配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\date_range\\DateRangePlaceholderIconSection',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 指定默认日期范围或编辑态回显。',
                    'builder' => 'app\\showcase\\service\\components\\form\\date_range\\DateRangeDefaultValueSection',
                ],
                [
                    'key' => 'style',
                    'title' => '样式变体',
                    'summary' => 'rounded、flush 等常见日期范围输入视觉样式。',
                    'builder' => 'app\\showcase\\service\\components\\form\\date_range\\DateRangeStyleSection',
                ],
                [
                    'key' => 'state',
                    'title' => '只读与禁用',
                    'summary' => 'readonly 与 disabled 状态展示。',
                    'builder' => 'app\\showcase\\service\\components\\form\\date_range\\DateRangeStateSection',
                ],
                [
                    'key' => 'native_options',
                    'title' => '原生 options 配置',
                    'summary' => '透传 AirDatepicker 原生参数，如 `dateFormat`、`multipleDatesSeparator`、`autoClose`。',
                    'builder' => 'app\\showcase\\service\\components\\form\\date_range\\DateRangeNativeOptionsSection',
                ],
                [
                    'key' => 'range_format',
                    'title' => '范围格式与分隔符',
                    'summary' => '说明范围输出格式与分隔符控制的典型组合。',
                    'builder' => 'app\\showcase\\service\\components\\form\\date_range\\DateRangeFormatSection',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把常见 date_range 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\date_range\\DateRangeProfileFormSection',
                ],
            ],
            'datetime.time' => [
                [
                    'key' => 'basic',
                    'title' => '基础用法',
                    'summary' => '最小可用的 time 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\time\\TimeBasicSection',
                ],
                [
                    'key' => 'placeholder_icon',
                    'title' => '占位符与图标',
                    'summary' => 'placeholder 与 icon 的组合配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\time\\TimePlaceholderIconSection',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 指定默认时间或编辑态回显。',
                    'builder' => 'app\\showcase\\service\\components\\form\\time\\TimeDefaultValueSection',
                ],
                [
                    'key' => 'style',
                    'title' => '样式变体',
                    'summary' => 'rounded、flush 等常见时间输入视觉样式。',
                    'builder' => 'app\\showcase\\service\\components\\form\\time\\TimeStyleSection',
                ],
                [
                    'key' => 'state',
                    'title' => '只读与禁用',
                    'summary' => 'readonly 与 disabled 状态展示。',
                    'builder' => 'app\\showcase\\service\\components\\form\\time\\TimeStateSection',
                ],
                [
                    'key' => 'native_options',
                    'title' => '原生 options 配置',
                    'summary' => '透传 AirDatepicker 原生参数，如 `timeFormat`、`hoursStep`、`minutesStep`。',
                    'builder' => 'app\\showcase\\service\\components\\form\\time\\TimeNativeOptionsSection',
                ],
                [
                    'key' => 'format_step',
                    'title' => '时间格式与步进',
                    'summary' => '说明输出时间格式与小时/分钟步进的典型组合。',
                    'builder' => 'app\\showcase\\service\\components\\form\\time\\TimeFormatStepSection',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把常见 time 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\time\\TimeProfileFormSection',
                ],
            ],
            'datetime.datetime' => [
                [
                    'key' => 'basic',
                    'title' => '基础用法',
                    'summary' => '最小可用的 datetime 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\datetime\\DatetimeBasicSection',
                ],
                [
                    'key' => 'placeholder_icon',
                    'title' => '占位符与图标',
                    'summary' => 'placeholder 与 icon 的组合配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\datetime\\DatetimePlaceholderIconSection',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 指定默认日期时间或编辑态回显。',
                    'builder' => 'app\\showcase\\service\\components\\form\\datetime\\DatetimeDefaultValueSection',
                ],
                [
                    'key' => 'style',
                    'title' => '样式变体',
                    'summary' => 'rounded、flush 等常见日期时间输入视觉样式。',
                    'builder' => 'app\\showcase\\service\\components\\form\\datetime\\DatetimeStyleSection',
                ],
                [
                    'key' => 'state',
                    'title' => '只读与禁用',
                    'summary' => 'readonly 与 disabled 状态展示。',
                    'builder' => 'app\\showcase\\service\\components\\form\\datetime\\DatetimeStateSection',
                ],
                [
                    'key' => 'native_options',
                    'title' => '原生 options 配置',
                    'summary' => '透传 AirDatepicker 原生参数，如 `dateFormat`、`timeFormat`、`minutesStep`。',
                    'builder' => 'app\\showcase\\service\\components\\form\\datetime\\DatetimeNativeOptionsSection',
                ],
                [
                    'key' => 'format_granularity',
                    'title' => '日期时间格式与粒度',
                    'summary' => '说明输出格式与分钟粒度控制的典型组合。',
                    'builder' => 'app\\showcase\\service\\components\\form\\datetime\\DatetimeFormatGranularitySection',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把常见 datetime 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\datetime\\DatetimeProfileFormSection',
                ],
            ],
            'datetime.datetime_range' => [
                [
                    'key' => 'basic',
                    'title' => '基础用法',
                    'summary' => '最小可用的 datetime_range 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\datetime_range\\DatetimeRangeBasicSection',
                ],
                [
                    'key' => 'placeholder_icon',
                    'title' => '占位符与图标',
                    'summary' => 'placeholder 与 icon 的组合配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\datetime_range\\DatetimeRangePlaceholderIconSection',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 指定默认时间段或编辑态回显。',
                    'builder' => 'app\\showcase\\service\\components\\form\\datetime_range\\DatetimeRangeDefaultValueSection',
                ],
                [
                    'key' => 'style',
                    'title' => '样式变体',
                    'summary' => 'rounded、flush 等常见日期时间范围输入视觉样式。',
                    'builder' => 'app\\showcase\\service\\components\\form\\datetime_range\\DatetimeRangeStyleSection',
                ],
                [
                    'key' => 'state',
                    'title' => '只读与禁用',
                    'summary' => 'readonly 与 disabled 状态展示。',
                    'builder' => 'app\\showcase\\service\\components\\form\\datetime_range\\DatetimeRangeStateSection',
                ],
                [
                    'key' => 'native_options',
                    'title' => '原生 options 配置',
                    'summary' => '透传 AirDatepicker 原生参数，如 `dateFormat`、`timeFormat`、`multipleDatesSeparator`。',
                    'builder' => 'app\\showcase\\service\\components\\form\\datetime_range\\DatetimeRangeNativeOptionsSection',
                ],
                [
                    'key' => 'range_format',
                    'title' => '范围格式与分隔符',
                    'summary' => '说明范围输出格式、分钟粒度与分隔符控制的典型组合。',
                    'builder' => 'app\\showcase\\service\\components\\form\\datetime_range\\DatetimeRangeFormatSection',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把常见 datetime_range 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\datetime_range\\DatetimeRangeProfileFormSection',
                ],
            ],
            'media.image' => [
                [
                    'key' => 'basic',
                    'title' => '基础上传',
                    'summary' => '最小可用的 image 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\image\\ImageBasicSection',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 回显单图或已有图片占位。',
                    'builder' => 'app\\showcase\\service\\components\\form\\image\\ImageDefaultValueSection',
                ],
                [
                    'key' => 'multiple_limit',
                    'title' => '多图与数量限制',
                    'summary' => '通过 multiple 开启多图并控制最大数量。',
                    'builder' => 'app\\showcase\\service\\components\\form\\image\\ImageMultipleLimitSection',
                ],
                [
                    'key' => 'driver_dir',
                    'title' => '上传驱动与目录',
                    'summary' => '通过 driver 与 dir 切换上传驱动和存储目录。',
                    'builder' => 'app\\showcase\\service\\components\\form\\image\\ImageDriverDirSection',
                ],
                [
                    'key' => 'button_control',
                    'title' => '按钮控制',
                    'summary' => 'upload、browser、clear、delete 等按钮开关控制。',
                    'builder' => 'app\\showcase\\service\\components\\form\\image\\ImageButtonControlSection',
                ],
                [
                    'key' => 'readonly_options',
                    'title' => '只读与原生配置',
                    'summary' => 'readonly 与原生 options 在上传组件中的组合方式。',
                    'builder' => 'app\\showcase\\service\\components\\form\\image\\ImageReadonlyOptionsSection',
                ],
                [
                    'key' => 'constraint',
                    'title' => '上传约束',
                    'summary' => '通过 allowedTypes、maxFileSize 等限制上传行为。',
                    'builder' => 'app\\showcase\\service\\components\\form\\image\\ImageConstraintSection',
                ],
                [
                    'key' => 'upload_endpoint',
                    'title' => '上传地址与附加参数',
                    'summary' => '通过自定义上传地址、附加参数和自动上传策略对接业务上传接口。',
                    'builder' => 'app\\showcase\\service\\components\\form\\image\\ImageUploadEndpointSection',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把常见 image 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\image\\ImageProfileFormSection',
                ],
            ],
            'media.file' => [
                [
                    'key' => 'basic',
                    'title' => '基础上传',
                    'summary' => '最小可用的 file 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\file\\FileBasicSection',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 回显单文件或已有文件占位。',
                    'builder' => 'app\\showcase\\service\\components\\form\\file\\FileDefaultValueSection',
                ],
                [
                    'key' => 'multiple_limit',
                    'title' => '多文件与数量限制',
                    'summary' => '通过 multiple 开启多文件并控制最大数量。',
                    'builder' => 'app\\showcase\\service\\components\\form\\file\\FileMultipleLimitSection',
                ],
                [
                    'key' => 'driver_dir',
                    'title' => '上传驱动与目录',
                    'summary' => '通过 driver 与 dir 切换上传驱动和存储目录。',
                    'builder' => 'app\\showcase\\service\\components\\form\\file\\FileDriverDirSection',
                ],
                [
                    'key' => 'button_control',
                    'title' => '按钮控制',
                    'summary' => 'upload、browser、download、clear、delete 等按钮开关控制。',
                    'builder' => 'app\\showcase\\service\\components\\form\\file\\FileButtonControlSection',
                ],
                [
                    'key' => 'readonly_download',
                    'title' => '只读与下载',
                    'summary' => 'readonly 与 download 在附件组件中的组合方式。',
                    'builder' => 'app\\showcase\\service\\components\\form\\file\\FileReadonlyDownloadSection',
                ],
                [
                    'key' => 'constraint',
                    'title' => '上传约束',
                    'summary' => '通过 allowedTypes、maxFileSize 等限制上传行为。',
                    'builder' => 'app\\showcase\\service\\components\\form\\file\\FileConstraintSection',
                ],
                [
                    'key' => 'upload_endpoint',
                    'title' => '上传地址与附加参数',
                    'summary' => '通过自定义上传地址、附加参数和自动上传策略对接业务上传接口。',
                    'builder' => 'app\\showcase\\service\\components\\form\\file\\FileUploadEndpointSection',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把常见 file 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\file\\FileProfileFormSection',
                ],
            ],
            'media.cropper' => [
                [
                    'key' => 'basic',
                    'title' => '基础裁剪',
                    'summary' => '最小可用的 cropper 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\cropper\\CropperBasicSection',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 回显已有图片并继续裁剪。',
                    'builder' => 'app\\showcase\\service\\components\\form\\cropper\\CropperDefaultValueSection',
                ],
                [
                    'key' => 'buttons',
                    'title' => '按钮组配置',
                    'summary' => '通过 buttons 控制 upload / url / select / delete 入口。',
                    'builder' => 'app\\showcase\\service\\components\\form\\cropper\\CropperButtonsSection',
                ],
                [
                    'key' => 'actions',
                    'title' => '裁剪动作',
                    'summary' => '通过 actions 控制缩放、旋转和翻转等操作。',
                    'builder' => 'app\\showcase\\service\\components\\form\\cropper\\CropperActionsSection',
                ],
                [
                    'key' => 'driver_dir',
                    'title' => '上传驱动与目录',
                    'summary' => '通过 driver 与 dir 切换上传驱动和存储目录。',
                    'builder' => 'app\\showcase\\service\\components\\form\\cropper\\CropperDriverDirSection',
                ],
                [
                    'key' => 'native_options',
                    'title' => '原生 options 配置',
                    'summary' => '通过 options 透传裁剪器原生配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\cropper\\CropperNativeOptionsSection',
                ],
                [
                    'key' => 'size_hint',
                    'title' => '固定尺寸提示',
                    'summary' => '通过 tips 与按钮组合强调目标尺寸与裁切要求。',
                    'builder' => 'app\\showcase\\service\\components\\form\\cropper\\CropperSizeHintSection',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把常见 cropper 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\cropper\\CropperProfileFormSection',
                ],
            ],
            'media.image_select' => [
                [
                    'key' => 'basic',
                    'title' => '基础选择',
                    'summary' => '最小可用的 image_select 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\image_select\\ImageSelectBasicSection',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 指定默认选中的图片。',
                    'builder' => 'app\\showcase\\service\\components\\form\\image_select\\ImageSelectDefaultValueSection',
                ],
                [
                    'key' => 'multiple',
                    'title' => '多选模式',
                    'summary' => '通过 multiple 开启多选图片选择。',
                    'builder' => 'app\\showcase\\service\\components\\form\\image_select\\ImageSelectMultipleSection',
                ],
                [
                    'key' => 'disabled',
                    'title' => '禁用状态',
                    'summary' => '通过 disabled 禁用全部或部分图片选项。',
                    'builder' => 'app\\showcase\\service\\components\\form\\image_select\\ImageSelectDisabledSection',
                ],
                [
                    'key' => 'layout',
                    'title' => '样式与布局',
                    'summary' => '通过 class 与 label_class 调整卡片布局密度。',
                    'builder' => 'app\\showcase\\service\\components\\form\\image_select\\ImageSelectLayoutSection',
                ],
                [
                    'key' => 'option_schema',
                    'title' => '选项结构',
                    'summary' => '说明字符串选项与对象选项两种配置结构。',
                    'builder' => 'app\\showcase\\service\\components\\form\\image_select\\ImageSelectOptionSchemaSection',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把常见 image_select 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\image_select\\ImageSelectProfileFormSection',
                ],
            ],
            'rich.ueditor' => [
                [
                    'key' => 'basic',
                    'title' => '基础编辑器',
                    'summary' => '最小可用的 ueditor 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\ueditor\\UeditorBasicSection',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 指定默认 HTML 内容或编辑态回显。',
                    'builder' => 'app\\showcase\\service\\components\\form\\ueditor\\UeditorDefaultValueSection',
                ],
                [
                    'key' => 'height',
                    'title' => '编辑器高度',
                    'summary' => '通过 options.initialFrameHeight 控制编辑区域高度。',
                    'builder' => 'app\\showcase\\service\\components\\form\\ueditor\\UeditorHeightSection',
                ],
                [
                    'key' => 'driver_dir',
                    'title' => '上传驱动与目录',
                    'summary' => '通过 driver 与 dir 切换上传驱动和资源目录。',
                    'builder' => 'app\\showcase\\service\\components\\form\\ueditor\\UeditorDriverDirSection',
                ],
                [
                    'key' => 'server_url',
                    'title' => '自定义 serverUrl',
                    'summary' => '通过 options.serverUrl 改写 UEditor 配置接口地址。',
                    'builder' => 'app\\showcase\\service\\components\\form\\ueditor\\UeditorServerUrlSection',
                ],
                [
                    'key' => 'native_options',
                    'title' => '原生 options 配置',
                    'summary' => '透传 UEditor 原生配置，如工具栏、自动浮动、字数统计。',
                    'builder' => 'app\\showcase\\service\\components\\form\\ueditor\\UeditorNativeOptionsSection',
                ],
                [
                    'key' => 'content_notice',
                    'title' => '内容安全提示',
                    'summary' => '说明 HTML 富文本入库、过滤与字段类型注意事项。',
                    'builder' => 'app\\showcase\\service\\components\\form\\ueditor\\UeditorContentNoticeSection',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把常见 ueditor 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\ueditor\\UeditorProfileFormSection',
                ],
            ],
            'rich.vditor' => [
                [
                    'key' => 'basic',
                    'title' => '基础编辑器',
                    'summary' => '最小可用的 vditor 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\vditor\\VditorBasicSection',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 指定默认 Markdown 内容或编辑态回显。',
                    'builder' => 'app\\showcase\\service\\components\\form\\vditor\\VditorDefaultValueSection',
                ],
                [
                    'key' => 'mode',
                    'title' => '编辑模式',
                    'summary' => '通过 options.mode 切换 wysiwyg、ir、sv 三种编辑模式。',
                    'builder' => 'app\\showcase\\service\\components\\form\\vditor\\VditorModeSection',
                ],
                [
                    'key' => 'driver_dir',
                    'title' => '上传驱动与目录',
                    'summary' => '通过 driver 与 dir 切换上传驱动和资源目录。',
                    'builder' => 'app\\showcase\\service\\components\\form\\vditor\\VditorDriverDirSection',
                ],
                [
                    'key' => 'toolbar',
                    'title' => '工具栏配置',
                    'summary' => '通过 options.toolbar 定义可见按钮与操作集。',
                    'builder' => 'app\\showcase\\service\\components\\form\\vditor\\VditorToolbarSection',
                ],
                [
                    'key' => 'native_options',
                    'title' => '原生 options 配置',
                    'summary' => '透传 Vditor 原生配置，如高度、计数器、预览行为与上传参数。',
                    'builder' => 'app\\showcase\\service\\components\\form\\vditor\\VditorNativeOptionsSection',
                ],
                [
                    'key' => 'content_notice',
                    'title' => '内容安全提示',
                    'summary' => '说明 Markdown 入库、HTML 白名单与上传资源治理注意事项。',
                    'builder' => 'app\\showcase\\service\\components\\form\\vditor\\VditorContentNoticeSection',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把常见 vditor 用法组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\vditor\\VditorProfileFormSection',
                ],
            ],
            'rich.transfer' => [
                [
                    'key' => 'basic',
                    'title' => '基础穿梭框',
                    'summary' => '最小可用的 transfer 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\transfer\\TransferSectionBuilder',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与回填',
                    'summary' => '通过 value 展示默认选中项与编辑态回填。',
                    'builder' => 'app\\showcase\\service\\components\\form\\transfer\\TransferSectionBuilder',
                ],
                [
                    'key' => 'disabled',
                    'title' => '禁用指定选项',
                    'summary' => '禁用全部或指定候选项，避免误分配。',
                    'builder' => 'app\\showcase\\service\\components\\form\\transfer\\TransferSectionBuilder',
                ],
                [
                    'key' => 'props',
                    'title' => '透传 props 配置',
                    'summary' => '自定义列表标题、筛选和移动交互方式。',
                    'builder' => 'app\\showcase\\service\\components\\form\\transfer\\TransferSectionBuilder',
                ],
                [
                    'key' => 'notice',
                    'title' => '选项规模与使用提示',
                    'summary' => '说明 transfer 的适用规模、值结构与选型边界。',
                    'builder' => 'app\\showcase\\service\\components\\form\\transfer\\TransferSectionBuilder',
                ],
                [
                    'key' => 'extension_usage',
                    'title' => '扩展项接入方式',
                    'summary' => '强调 transfer 当前通过扩展项门面接入，而不是内置 Field 映射。',
                    'builder' => 'app\\showcase\\service\\components\\form\\transfer\\TransferSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把 transfer 与标题等字段组合成真实角色分配表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\transfer\\TransferSectionBuilder',
                ],
            ],
            'rich.amap' => [
                [
                    'key' => 'basic',
                    'title' => '基础选点',
                    'summary' => '最小可用的高德地图选点配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与地址回填',
                    'summary' => '通过 value 和 address 回显已有坐标与地址。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'address_init',
                    'title' => '仅地址初始化',
                    'summary' => '无坐标时通过 address 直接初始化地图位置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'center_zoom',
                    'title' => '中心点与缩放',
                    'summary' => '控制地图默认中心点、缩放级别和画布高度。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'address_field',
                    'title' => '地址字段与占位符',
                    'summary' => '自定义地址字段名和搜索占位符。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'readonly',
                    'title' => '只读模式',
                    'summary' => '用于详情页或审批页的只读地图展示。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'vendor_options',
                    'title' => 'Key 与安全密钥',
                    'summary' => '高德地图特有的 Key 与 securityJsCode 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把地图选点与门店名称、联系人等字段组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
            ],
            'rich.bmap' => [
                [
                    'key' => 'basic',
                    'title' => '基础选点',
                    'summary' => '最小可用的百度地图选点配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与地址回填',
                    'summary' => '通过 value 和 address 回显已有坐标与地址。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'address_init',
                    'title' => '仅地址初始化',
                    'summary' => '无坐标时通过 address 直接初始化地图位置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'center_zoom',
                    'title' => '中心点与缩放',
                    'summary' => '控制地图默认中心点、缩放级别和画布高度。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'address_field',
                    'title' => '地址字段与占位符',
                    'summary' => '自定义地址字段名和搜索占位符。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'readonly',
                    'title' => '只读模式',
                    'summary' => '用于详情页或审批页的只读地图展示。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'vendor_options',
                    'title' => 'AK 与区域限制',
                    'summary' => '百度地图特有的 AK 和 region 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把地图选点与门店名称、联系人等字段组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
            ],
            'rich.qmap' => [
                [
                    'key' => 'basic',
                    'title' => '基础选点',
                    'summary' => '最小可用的腾讯地图选点配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'default_value',
                    'title' => '默认值与地址回填',
                    'summary' => '通过 value 和 address 回显已有坐标与地址。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'address_init',
                    'title' => '仅地址初始化',
                    'summary' => '无坐标时通过 address 直接初始化地图位置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'center_zoom',
                    'title' => '中心点与缩放',
                    'summary' => '控制地图默认中心点、缩放级别和画布高度。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'address_field',
                    'title' => '地址字段与占位符',
                    'summary' => '自定义地址字段名和搜索占位符。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'readonly',
                    'title' => '只读模式',
                    'summary' => '用于详情页或审批页的只读地图展示。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'vendor_options',
                    'title' => 'Key 与逆地址配置',
                    'summary' => '腾讯地图特有的 Key、get_poi 和逆地址参数。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把地图选点与门店名称、联系人等字段组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\map\\MapSectionBuilder',
                ],
            ],
            'rich.tabs' => [
                [
                    'key' => 'basic',
                    'title' => '基础 HTML 标签页',
                    'summary' => '最基础的 HTML 内容分组标签页。',
                    'builder' => 'app\\showcase\\service\\components\\form\\tabs\\TabsSectionBuilder',
                ],
                [
                    'key' => 'icon',
                    'title' => '图标标签页',
                    'summary' => '在标签标题中加入图标 HTML。',
                    'builder' => 'app\\showcase\\service\\components\\form\\tabs\\TabsSectionBuilder',
                ],
                [
                    'key' => 'right',
                    'title' => 'right 右侧标签',
                    'summary' => '支持把某个标签或整组标签推到右侧。',
                    'builder' => 'app\\showcase\\service\\components\\form\\tabs\\TabsSectionBuilder',
                ],
                [
                    'key' => 'fill',
                    'title' => 'fill 等宽标签',
                    'summary' => '使用 fill 让标签项平均铺满宽度。',
                    'builder' => 'app\\showcase\\service\\components\\form\\tabs\\TabsSectionBuilder',
                ],
                [
                    'key' => 'disabled',
                    'title' => 'disabled 禁用标签',
                    'summary' => '禁用指定标签或全部标签。',
                    'builder' => 'app\\showcase\\service\\components\\form\\tabs\\TabsSectionBuilder',
                ],
                [
                    'key' => 'form_items',
                    'title' => '表单项数组内容',
                    'summary' => '直接在标签内容中嵌入表单项数组。',
                    'builder' => 'app\\showcase\\service\\components\\form\\tabs\\TabsSectionBuilder',
                ],
                [
                    'key' => 'mixed_content',
                    'title' => 'HTML 与表单混合内容',
                    'summary' => '混合使用 HTML 字符串和表单项内容。',
                    'builder' => 'app\\showcase\\service\\components\\form\\tabs\\TabsSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把 tabs 用于真实的多分组配置表单。',
                    'builder' => 'app\\showcase\\service\\components\\form\\tabs\\TabsSectionBuilder',
                ],
            ],
            'rich.table' => [
                [
                    'key' => 'basic',
                    'title' => '基础表格',
                    'summary' => '最小可用的 table 配置。',
                    'builder' => 'app\\showcase\\service\\components\\form\\table\\TableSectionBuilder',
                ],
                [
                    'key' => 'value_rows',
                    'title' => 'value 回显表体',
                    'summary' => '直接通过 value 传入表体数据，兼容旧写法。',
                    'builder' => 'app\\showcase\\service\\components\\form\\table\\TableSectionBuilder',
                ],
                [
                    'key' => 'merge_headers',
                    'title' => '多表头与合并单元格',
                    'summary' => '使用 headers、rowspan、colspan 组织复杂表头结构。',
                    'builder' => 'app\\showcase\\service\\components\\form\\table\\TableSectionBuilder',
                ],
                [
                    'key' => 'raw_html',
                    'title' => '单元格 raw 与 HTML',
                    'summary' => '控制单元格是否按 HTML 原样输出。',
                    'builder' => 'app\\showcase\\service\\components\\form\\table\\TableSectionBuilder',
                ],
                [
                    'key' => 'style_wrapper',
                    'title' => '样式类与外层容器',
                    'summary' => '使用 table_class 与 wrapper_class 控制表格外观。',
                    'builder' => 'app\\showcase\\service\\components\\form\\table\\TableSectionBuilder',
                ],
                [
                    'key' => 'empty_text',
                    'title' => '空数据占位',
                    'summary' => '空表体时通过 empty_text 输出占位文案。',
                    'builder' => 'app\\showcase\\service\\components\\form\\table\\TableSectionBuilder',
                ],
                [
                    'key' => 'import_preview',
                    'title' => '导入预览场景',
                    'summary' => '把解析结果先展示为只读预览表，再决定是否提交。',
                    'builder' => 'app\\showcase\\service\\components\\form\\table\\TableSectionBuilder',
                ],
                [
                    'key' => 'profile_form',
                    'title' => '业务表单片段',
                    'summary' => '把 table 与文本字段组合成真实业务表单片段。',
                    'builder' => 'app\\showcase\\service\\components\\form\\table\\TableSectionBuilder',
                ],
            ],
        ];
    }
}
