<?php
declare(strict_types=1);

namespace app\showcase\service\registry;

/**
 * Showcase 表单组件目录
 */
final class ShowcaseFormComponentCatalog
{
    /**
     * @return array<string, array<string, string>>
     */
    public static function groups(): array
    {
        return [
            'basic' => ['title' => '基础输入', 'summary' => '文本、数字、状态与基础排版'],
            'choice' => ['title' => '选择与联动', 'summary' => '下拉、单选、联动和远程搜索'],
            'datetime' => ['title' => '时间与日期', 'summary' => '日期、时间与范围选择'],
            'media' => ['title' => '上传与媒体', 'summary' => '图片、文件和裁剪'],
            'rich' => ['title' => '富文本与复杂结构', 'summary' => '编辑器、扩展项和组合结构'],
        ];
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    public static function components(): array
    {
        return [
            'basic.text' => [
                'key' => 'basic.text',
                'renderer' => 'form',
                'group' => 'basic',
                'group_title' => '基础输入',
                'title' => 'text 单行文本框',
                'summary' => '覆盖文本输入框的主要参数与常用组合方式。',
                'status' => 'available',
                'tags' => ['占位提示', '长度限制', '前后缀', '只读/禁用', '自动补全'],
                'doc_links' => ['docs/表单/text.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/TextComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 text 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\TextComponentPage',
            ],
            'basic.textarea' => [
                'key' => 'basic.textarea',
                'renderer' => 'form',
                'group' => 'basic',
                'group_title' => '基础输入',
                'title' => 'textarea 多行文本',
                'summary' => '覆盖多行文本输入、行数控制、自动增高与真实业务组合方式。',
                'status' => 'available',
                'tags' => ['占位提示', '长度限制', '默认行数', '自动增高'],
                'doc_links' => ['docs/表单/textarea.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/TextareaComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 textarea 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\TextareaComponentPage',
            ],
            'basic.number' => [
                'key' => 'basic.number',
                'renderer' => 'form',
                'group' => 'basic',
                'group_title' => '基础输入',
                'title' => 'number 数字输入',
                'summary' => '覆盖数字输入的范围约束、步进值、单位提示与真实业务组合方式。',
                'status' => 'available',
                'tags' => ['步进值', '最小/最大值', '默认值', '前后缀'],
                'doc_links' => ['docs/表单/number.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/NumberComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 number 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\NumberComponentPage',
            ],
            'basic.password' => [
                'key' => 'basic.password',
                'renderer' => 'form',
                'group' => 'basic',
                'group_title' => '基础输入',
                'title' => 'password 密码框',
                'summary' => '覆盖密码输入的隐藏展示、强度提示、长度限制、状态控制与真实业务组合方式。',
                'status' => 'available',
                'tags' => ['显示切换', '强度提示', '长度限制', '只读/禁用'],
                'doc_links' => ['docs/表单/password.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/PasswordComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 password 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\PasswordComponentPage',
            ],
            'basic.switch' => [
                'key' => 'basic.switch',
                'renderer' => 'form',
                'group' => 'basic',
                'group_title' => '基础输入',
                'title' => 'switch 开关',
                'summary' => '覆盖二元状态切换、默认值、禁用态与后端提交注意事项。',
                'status' => 'available',
                'tags' => ['开关状态', '默认值', '禁用态', '提交处理'],
                'doc_links' => ['docs/表单/switch.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/SwitchComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 switch 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\SwitchComponentPage',
            ],
            'basic.hidden' => [
                'key' => 'basic.hidden',
                'renderer' => 'form',
                'group' => 'basic',
                'group_title' => '基础输入',
                'title' => 'hidden 隐藏域',
                'summary' => '覆盖隐藏值传递、编辑态主键回填与安全提示等常见 hidden 使用方式。',
                'status' => 'available',
                'tags' => ['主键传递', '上下文标记', '默认值', '安全提示'],
                'doc_links' => ['docs/表单/hidden.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/HiddenComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 hidden 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\HiddenComponentPage',
            ],
            'basic.html' => [
                'key' => 'basic.html',
                'renderer' => 'form',
                'group' => 'basic',
                'group_title' => '基础输入',
                'title' => 'html HTML 内容',
                'summary' => '覆盖说明区、警告区、卡片区与状态区等常见 html 内容插入方式。',
                'status' => 'available',
                'tags' => ['提示区', '警告区', '信息卡片', '状态展示'],
                'doc_links' => ['docs/表单/html.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/HtmlComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 html 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\HtmlComponentPage',
            ],
            'basic.static' => [
                'key' => 'basic.static',
                'renderer' => 'form',
                'group' => 'basic',
                'group_title' => '基础输入',
                'title' => 'static 静态文本',
                'summary' => '覆盖只读展示、send 提交、raw HTML 与关联信息展示等 static 常见用法。',
                'status' => 'available',
                'tags' => ['只读展示', 'send 提交', 'raw HTML', '关联信息'],
                'doc_links' => ['docs/表单/static.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/StaticComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 static 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\StaticComponentPage',
            ],
            'basic.button' => [
                'key' => 'basic.button',
                'renderer' => 'form',
                'group' => 'basic',
                'group_title' => '基础输入',
                'title' => 'button 按钮',
                'summary' => '覆盖颜色、图标、链接、形状、禁用态与 SVG 图标等 button 常见能力。',
                'status' => 'available',
                'tags' => ['颜色', '图标', '链接跳转', '形状变体'],
                'doc_links' => ['docs/表单/button.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/ButtonComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 button 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\ButtonComponentPage',
            ],
            'basic.button_group' => [
                'key' => 'basic.button_group',
                'renderer' => 'form',
                'group' => 'basic',
                'group_title' => '基础输入',
                'title' => 'button_group 按钮组',
                'summary' => '覆盖视图切换、垂直布局、图标按钮组与值回填等 button_group 常见用法。',
                'status' => 'available',
                'tags' => ['视图切换', '默认值', '图标按钮', '垂直布局'],
                'doc_links' => ['docs/表单/buttonGroup.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/ButtonGroupComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 button_group 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\ButtonGroupComponentPage',
            ],
            'basic.mask' => [
                'key' => 'basic.mask',
                'renderer' => 'form',
                'group' => 'basic',
                'group_title' => '基础输入',
                'title' => 'mask 格式化输入',
                'summary' => '覆盖手机号、日期、证件号和业务编号等常见格式化输入场景。',
                'status' => 'available',
                'tags' => ['手机号', '日期格式', '证件号', '编号格式'],
                'doc_links' => ['docs/表单/mask.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/MaskComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 mask 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\MaskComponentPage',
            ],
            'choice.radio' => [
                'key' => 'choice.radio',
                'renderer' => 'form',
                'group' => 'choice',
                'group_title' => '选择与联动',
                'title' => 'radio 单选框',
                'summary' => '覆盖单选框的选项配置、默认值、inline 展示、禁用态与条件联动场景。',
                'status' => 'available',
                'tags' => ['单选', '默认值', 'inline', '条件联动'],
                'doc_links' => ['docs/表单/radio.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/RadioComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 radio 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\RadioComponentPage',
            ],
            'choice.radio_group' => [
                'key' => 'choice.radio_group',
                'renderer' => 'form',
                'group' => 'choice',
                'group_title' => '选择与联动',
                'title' => 'radio_group 单选标签组',
                'summary' => '覆盖卡片式单选的默认值、富文案展示、禁用态、联动与业务组合方式。',
                'status' => 'available',
                'tags' => ['卡片单选', '默认值', '富文案', '套餐卡片', '条件联动'],
                'doc_links' => ['docs/表单/radioGroup.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/RadioGroupComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 radio_group 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\RadioGroupComponentPage',
            ],
            'choice.select' => [
                'key' => 'choice.select',
                'renderer' => 'form',
                'group' => 'choice',
                'group_title' => '选择与联动',
                'title' => 'select 下拉选择',
                'summary' => '覆盖单选、多选、分组、禁用选项、占位符与扩展参数等常见下拉场景。',
                'status' => 'available',
                'tags' => ['默认值', '多选', '分组', '禁用选项'],
                'doc_links' => ['docs/表单/select.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/SelectComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 select 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\SelectComponentPage',
            ],
            'choice.select2' => [
                'key' => 'choice.select2',
                'renderer' => 'form',
                'group' => 'choice',
                'group_title' => '选择与联动',
                'title' => 'select2 增强下拉选择',
                'summary' => '覆盖搜索、多选、分组、异步加载、原生配置等增强下拉场景。',
                'status' => 'available',
                'tags' => ['搜索', '多选', '异步加载', '原生配置'],
                'doc_links' => ['docs/表单/select2.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/Select2ComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 select2 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\Select2ComponentPage',
            ],
            'choice.linkage' => [
                'key' => 'choice.linkage',
                'renderer' => 'form',
                'group' => 'choice',
                'group_title' => '选择与联动',
                'title' => 'linkage 多级联动',
                'summary' => '覆盖远程数据源、多级回填、按级别请求和末级多选等 linkage 常见联动能力。',
                'status' => 'available',
                'tags' => ['远程数据源', '多级联动', '默认值回填', '末级多选'],
                'doc_links' => ['docs/表单/linkage.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/LinkageComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 linkage 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\LinkageComponentPage',
            ],
            'choice.linkages' => [
                'key' => 'choice.linkages',
                'renderer' => 'form',
                'group' => 'choice',
                'group_title' => '选择与联动',
                'title' => 'linkages 快速联动',
                'summary' => '覆盖内置接口、数据库表映射、层级命名和过滤条件等 linkages 快速联动能力。',
                'status' => 'available',
                'tags' => ['内置接口', '数据库表', '层级配置', '默认值回填'],
                'doc_links' => ['docs/表单/linkages.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/LinkagesComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 linkages 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\LinkagesComponentPage',
            ],
            'choice.checkbox' => [
                'key' => 'choice.checkbox',
                'renderer' => 'form',
                'group' => 'choice',
                'group_title' => '选择与联动',
                'title' => 'checkbox 多选框',
                'summary' => '覆盖标准多选框的默认值、横向排列、备注说明、禁用态与业务组合方式。',
                'status' => 'available',
                'tags' => ['多选', '默认值', '备注说明', 'inline'],
                'doc_links' => ['docs/表单/checkbox.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/CheckboxComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 checkbox 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\CheckboxComponentPage',
            ],
            'choice.checkbox_group' => [
                'key' => 'choice.checkbox_group',
                'renderer' => 'form',
                'group' => 'choice',
                'group_title' => '选择与联动',
                'title' => 'checkbox_group 多选标签组',
                'summary' => '覆盖卡片式多选的默认值、禁用态、必填提示和真实业务组合方式。',
                'status' => 'available',
                'tags' => ['卡片多选', '默认值', '禁用状态', '必填提示'],
                'doc_links' => ['docs/表单/checkboxGroup.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/CheckboxGroupComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 checkbox_group 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\CheckboxGroupComponentPage',
            ],
            'choice.select_group' => [
                'key' => 'choice.select_group',
                'renderer' => 'form',
                'group' => 'choice',
                'group_title' => '选择与联动',
                'title' => 'select_group 多选标签',
                'summary' => '覆盖标签式多选的默认值、圆角样式、禁用态和业务组合方式。',
                'status' => 'available',
                'tags' => ['标签多选', '默认值', '圆角样式', '禁用状态'],
                'doc_links' => ['docs/表单/selectGroup.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/SelectGroupComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 select_group 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\SelectGroupComponentPage',
            ],
            'choice.tags' => [
                'key' => 'choice.tags',
                'renderer' => 'form',
                'group' => 'choice',
                'group_title' => '选择与联动',
                'title' => 'tags 标签输入',
                'summary' => '覆盖标签输入的默认值、只读态、白名单配置和业务组合方式。',
                'status' => 'available',
                'tags' => ['标签输入', '默认值', '白名单', '只读状态'],
                'doc_links' => ['docs/表单/tags.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/TagsComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 tags 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\TagsComponentPage',
            ],
            'choice.color' => [
                'key' => 'choice.color',
                'renderer' => 'form',
                'group' => 'choice',
                'group_title' => '选择与联动',
                'title' => 'color 取色器',
                'summary' => '覆盖自由取色、透明度、预设色与交互开关等常见取色器配置。',
                'status' => 'available',
                'tags' => ['主题色', '透明度', '预设色', 'Coloris'],
                'doc_links' => ['docs/表单/color.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/ColorComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 color 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\ColorComponentPage',
            ],
            'choice.color_select' => [
                'key' => 'choice.color_select',
                'renderer' => 'form',
                'group' => 'choice',
                'group_title' => '选择与联动',
                'title' => 'color_select 预设颜色选择',
                'summary' => '覆盖预设颜色、圆形样式、多选和禁用态等常见颜色选择器配置。',
                'status' => 'available',
                'tags' => ['预设颜色', '圆形样式', '多选', '禁用态'],
                'doc_links' => ['docs/表单/colorSelect.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/ColorSelectComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 color_select 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\ColorSelectComponentPage',
            ],
            'choice.icon' => [
                'key' => 'choice.icon',
                'renderer' => 'form',
                'group' => 'choice',
                'group_title' => '选择与联动',
                'title' => 'icon 图标选择器',
                'summary' => '覆盖默认值回显、占位符、扩展图标库和配置提示等常见图标选择器能力。',
                'status' => 'available',
                'tags' => ['图标库', '默认值回显', '扩展库', '占位符'],
                'doc_links' => ['docs/表单/icon.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/IconComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 icon 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\IconComponentPage',
            ],
            'datetime.date' => [
                'key' => 'datetime.date',
                'renderer' => 'form',
                'group' => 'datetime',
                'group_title' => '时间与日期',
                'title' => 'date 日期选择器',
                'summary' => '覆盖单日期输入的默认值、图标、样式、原生 options 与业务组合方式。',
                'status' => 'available',
                'tags' => ['默认值', '图标', '样式变体', '原生配置'],
                'doc_links' => ['docs/表单/date.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/DateComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 date 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\DateComponentPage',
            ],
            'datetime.date_range' => [
                'key' => 'datetime.date_range',
                'renderer' => 'form',
                'group' => 'datetime',
                'group_title' => '时间与日期',
                'title' => 'date_range 日期范围选择器',
                'summary' => '覆盖日期范围输入的默认值、图标、样式、分隔符、范围格式与业务组合方式。',
                'status' => 'available',
                'tags' => ['范围选择', '默认值', '图标', '分隔符'],
                'doc_links' => ['docs/表单/dateRange.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/DateRangeComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 date_range 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\DateRangeComponentPage',
            ],
            'datetime.time' => [
                'key' => 'datetime.time',
                'renderer' => 'form',
                'group' => 'datetime',
                'group_title' => '时间与日期',
                'title' => 'time 时间选择器',
                'summary' => '覆盖纯时间输入的默认值、图标、样式、步进粒度与业务组合方式。',
                'status' => 'available',
                'tags' => ['默认值', '图标', '样式变体', '步进'],
                'doc_links' => ['docs/表单/time.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/TimeComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 time 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\TimeComponentPage',
            ],
            'datetime.datetime' => [
                'key' => 'datetime.datetime',
                'renderer' => 'form',
                'group' => 'datetime',
                'group_title' => '时间与日期',
                'title' => 'datetime 日期时间选择器',
                'summary' => '覆盖日期时间组合输入的默认值、图标、样式、格式控制与业务组合方式。',
                'status' => 'available',
                'tags' => ['默认值', '图标', '样式变体', '格式控制'],
                'doc_links' => ['docs/表单/datetime.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/DatetimeComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 datetime 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\DatetimeComponentPage',
            ],
            'datetime.datetime_range' => [
                'key' => 'datetime.datetime_range',
                'renderer' => 'form',
                'group' => 'datetime',
                'group_title' => '时间与日期',
                'title' => 'datetime_range 日期时间范围选择器',
                'summary' => '覆盖日期时间范围输入的默认值、图标、样式、分隔符、范围格式与业务组合方式。',
                'status' => 'available',
                'tags' => ['范围选择', '默认值', '图标', '分隔符'],
                'doc_links' => ['docs/表单/datetimeRange.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/DatetimeRangeComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 datetime_range 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\DatetimeRangeComponentPage',
            ],
            'media.image' => [
                'key' => 'media.image',
                'renderer' => 'form',
                'group' => 'media',
                'group_title' => '上传与媒体',
                'title' => 'image 图片上传',
                'summary' => '覆盖单图、多图、驱动目录、上传约束、按钮控制与业务组合方式。',
                'status' => 'available',
                'tags' => ['多图上传', '默认值', '上传驱动', '按钮控制'],
                'doc_links' => ['docs/表单/image.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/ImageComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 image 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\ImageComponentPage',
            ],
            'media.file' => [
                'key' => 'media.file',
                'renderer' => 'form',
                'group' => 'media',
                'group_title' => '上传与媒体',
                'title' => 'file 文件上传',
                'summary' => '覆盖单文件、多文件、下载按钮、上传约束与业务组合方式。',
                'status' => 'available',
                'tags' => ['多文件上传', '默认值', '下载按钮', '上传驱动'],
                'doc_links' => ['docs/表单/file.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/FileComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 file 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\FileComponentPage',
            ],
            'media.cropper' => [
                'key' => 'media.cropper',
                'renderer' => 'form',
                'group' => 'media',
                'group_title' => '上传与媒体',
                'title' => 'cropper 图片裁剪',
                'summary' => '覆盖裁剪按钮、操作动作、上传驱动、固定尺寸与业务组合方式。',
                'status' => 'available',
                'tags' => ['裁剪按钮', '裁剪动作', '上传驱动', '固定尺寸'],
                'doc_links' => ['docs/表单/cropper.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/CropperComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 cropper 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\CropperComponentPage',
            ],
            'media.image_select' => [
                'key' => 'media.image_select',
                'renderer' => 'form',
                'group' => 'media',
                'group_title' => '上传与媒体',
                'title' => 'image_select 图片选择器',
                'summary' => '覆盖预设图片单选、多选、禁用、布局样式与业务组合方式。',
                'status' => 'available',
                'tags' => ['预设图片', '多选', '禁用状态', '布局样式'],
                'doc_links' => ['docs/表单/imageSelect.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/ImageSelectComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 image_select 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\ImageSelectComponentPage',
            ],
            'rich.ueditor' => [
                'key' => 'rich.ueditor',
                'renderer' => 'form',
                'group' => 'rich',
                'group_title' => '富文本与复杂结构',
                'title' => 'ueditor 富文本编辑器',
                'summary' => '覆盖默认内容、高度、上传驱动、自定义 serverUrl、原生配置与业务组合方式。',
                'status' => 'available',
                'tags' => ['富文本', '默认值', '上传驱动', 'serverUrl'],
                'doc_links' => ['docs/表单/ueditor.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/UeditorComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 ueditor 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\UeditorComponentPage',
            ],
            'rich.vditor' => [
                'key' => 'rich.vditor',
                'renderer' => 'form',
                'group' => 'rich',
                'group_title' => '富文本与复杂结构',
                'title' => 'vditor Markdown 编辑器',
                'summary' => '覆盖默认内容、编辑模式、上传驱动、工具栏、原生配置与业务组合方式。',
                'status' => 'available',
                'tags' => ['Markdown', '默认值', '上传驱动', '工具栏'],
                'doc_links' => ['docs/表单/vditor.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/VditorComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 vditor 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\VditorComponentPage',
            ],
            'rich.transfer' => [
                'key' => 'rich.transfer',
                'renderer' => 'form',
                'group' => 'rich',
                'group_title' => '富文本与复杂结构',
                'title' => 'transfer 穿梭框',
                'summary' => '覆盖双栏分配、默认值、禁用项、props 透传和扩展项接入方式。',
                'status' => 'available',
                'tags' => ['双栏分配', '默认值回填', '禁用项', 'props 配置'],
                'doc_links' => ['docs/表单/transfer.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/TransferComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 transfer 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'extend/form/transfer/Transfer.php',
                        'label' => '扩展项门面',
                        'description' => 'transfer 当前通过独立扩展项门面接入。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\TransferComponentPage',
            ],
            'rich.amap' => [
                'key' => 'rich.amap',
                'renderer' => 'form',
                'group' => 'rich',
                'group_title' => '富文本与复杂结构',
                'title' => 'amap 高德地图',
                'summary' => '覆盖高德地图 Key、安全密钥、地址回填、只读模式与业务选点等 amap 常见能力。',
                'status' => 'available',
                'tags' => ['高德 Key', '安全密钥', '地址字段', '地图选点'],
                'doc_links' => ['docs/表单/amap.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/MapComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装地图类组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\MapComponentPage',
            ],
            'rich.bmap' => [
                'key' => 'rich.bmap',
                'renderer' => 'form',
                'group' => 'rich',
                'group_title' => '富文本与复杂结构',
                'title' => 'bmap 百度地图',
                'summary' => '覆盖百度地图 AK、区域限制、地址回填、只读模式与业务选点等 bmap 常见能力。',
                'status' => 'available',
                'tags' => ['百度 AK', '区域限制', '地址字段', '地图选点'],
                'doc_links' => ['docs/表单/bmap.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/MapComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装地图类组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\MapComponentPage',
            ],
            'rich.qmap' => [
                'key' => 'rich.qmap',
                'renderer' => 'form',
                'group' => 'rich',
                'group_title' => '富文本与复杂结构',
                'title' => 'qmap 腾讯地图',
                'summary' => '覆盖腾讯地图 Key、逆地址配置、地址回填、只读模式与业务选点等 qmap 常见能力。',
                'status' => 'available',
                'tags' => ['腾讯 Key', '逆地址解析', '地址字段', '地图选点'],
                'doc_links' => ['docs/表单/qmap.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/MapComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装地图类组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\MapComponentPage',
            ],
            'rich.tabs' => [
                'key' => 'rich.tabs',
                'renderer' => 'form',
                'group' => 'rich',
                'group_title' => '富文本与复杂结构',
                'title' => 'tabs 标签分组',
                'summary' => '覆盖 HTML 标签页、图标标签、等宽布局与表单内容分组等 tabs 常见用法。',
                'status' => 'available',
                'tags' => ['标签分组', '图标标签', '表单内容', '禁用标签'],
                'doc_links' => ['docs/表单/tabs.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/TabsComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 tabs 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\TabsComponentPage',
            ],
            'rich.table' => [
                'key' => 'rich.table',
                'renderer' => 'form',
                'group' => 'rich',
                'group_title' => '富文本与复杂结构',
                'title' => 'table 表格展示',
                'summary' => '覆盖只读表格、多表头、合并单元格、HTML 单元格和导入预览等 table 常见展示能力。',
                'status' => 'available',
                'tags' => ['多表头', '合并单元格', '只读展示', '导入预览'],
                'doc_links' => ['docs/表单/table.md'],
                'source_refs' => [
                    [
                        'path' => 'app/showcase/service/components/form/TableComponentPage.php',
                        'label' => '组件页构建器',
                        'description' => '负责组装 table 组件页的总览、参数组与能力块。',
                    ],
                    [
                        'path' => 'app/showcase/controller/admin/Form.php',
                        'label' => '专题控制器',
                        'description' => '承接组件卡片列表与组件详情页入口。',
                    ],
                ],
                'builder' => 'app\\showcase\\service\\components\\form\\TableComponentPage',
            ],
        ];
    }
}
